### ISSUE TITLE
How to increase security

### ISSUE THREAD

**Issue by wimjongman** [eureka-bpo/p2repository.com#1]
Thank you for this service. 🙏

How can we know that what you provide as bundles is safe?

**Comment by eureka-bpo** [comment]
Each p2-repository has file "artifacts.xml" (possible with jar or xz extension). This file contains a list of bundles and their checksums (usually SHA-512, SHA-256, sometimes MD-5). All these algorithms are supported by maven and can be used to validate jars of bundles. Content of bundles is transmitted by service without modification, checksum remains unchanged.

Service generates maven-specific artifacts: pom.xml, metadata-files - to adapt p2-repository structure for usage with maven.

**Comment by wimjongman** [comment]
Thanks for getting back so quickly. Please do not take this as being ungrateful. I am just being paranoid,

Is it not possible for you to repackage? How can consumers be sure that the content you are redistribution matches the original content?

**Comment by eureka-bpo** [comment]
> Is it not possible for you to repackage?

Service stores only metadata of p2-artifacts, not their binary content. For binary content service serves as proxy between customer and one of p2-repository mirror.

> How can consumers be sure that the content you are redistribution matches the original content?

Maven resolver proposes [different strategies](https://maven.apache.org/resolver/expected-checksums.html) to validate checksums. If default validation is not enough, customer can download artifacts.xml, extract checksums for all p2-repository artifacts and use it to validate service output. In this case validation will be absolute independent.

**Comment by wimjongman** [comment]
Why the title change?

**Comment by eureka-bpo** [comment]
Maven enforcer custom rule [require-p2-artifact-checksum](https://github.com/eureka-bpo/require-p2-artifact-checksum) has been prepared, which validates downloaded files with hashes received directly from p2 repository. Suppose, this is highest level of security: it works absolutely without intermediaries.

<img alt="How it works?" src="https://www.planttext.com/api/plantuml/svg/VLDDRvmm4BtpAwQ95BKhmKeSSuZIGvLBgqRfgThbC343EEklZEsbwQ-l3Kl8Ab4F23H-yzwyD-RM1-GGjIeAbpwaa0vDW8lVDZBym2CPk6VxH29S07fuqUxowtF4S_1cyuluA0LjDdkpsmqXE7-ztOxZMBcQoLalW-MNIbYzXVlwuQpID1EpdndEYN-oxAL1bPfWxPhmhYwAdcrqfocPl5L7uW90MUkWimo4Oe3Crw487eID9gHpo3QWl5aqhq5dYj8x4hAJ8d4zH_8pz8I1Ck5Jspji9nLDmAggflSdnzXhX43sBmIEz4RHljhCjQkL_2RxoJLNPoMxZfOAYuDLw-hzM1_Yvfd8j4L-vhmkl-DexfXIPkkgUXc6-3WjY2BJ0Sj7PxSv1ybKkhfSk4ina3ZugE5_Xqq3tqpQW226XwW8TgFbWuSsDQJvngIsDtPPRXfzlIHDyRgUAP8vaDbZzhNki_gZ5PIWf0zWEq2btknQKy0M0y9dQOIAhJGz3EW7yb-A9PUJp4GjK8ceC10i7lnqXSuozO2ctPkKKhgbDDauaKB7LiF7ZkRiisHncpxJl_OF" />

> Why the title change?

Title has been changed because of security is not a binary term: is anything safe or not safe. There are 50 grades of security and each user can have possibility select what he/she want. This enforcer rule gives such possibility.

**Comment by wimjongman** [comment]
Thank you!
